export default {
  "index": { "display": "hidden" },
  "mo-dau": "1. Giới thiệu GameKit",
  "hdsd": "2. Hướng dẫn sử dụng Makecode Arcade",
  "nap-code": "3. Nạp code cho GameKit",
  "nhan-vat": "4. Đưa nhân vật vào trò chơi",
  "vi-tri": "5. Thiết lập vị trí của nhân vật",
  "dieu-khien": "6. Điều khiển hoạt động nhân vật",
  "bat-nay": "7. Bật nảy khi nhân vật gặp tường",
  "hieu-ung": "8. Tạo hiệu ứng tuyết rơi",
  "ky-nang": "9. Tạo kỹ năng cho nhân vật",
  "xe-chay": "10. Tạo hiệu ứng xe chạy",
  "nut-nhan": "11. Thao tác với nút nhấn",
  "chu-chay": "12. Tạo hiệu ứng chữ chạy trên màn hình",
  "an-banh": "13. Game: Trò chơi ăn bánh",
  "bong-hoa": "14. Game: Bông hoa hạnh phúc",
  "qua-chanh": "15. Game: Quả chanh mọng nước",
  "may-bay": "16. Game: Bắn máy bay",
  "me-cung": "17. Game: Phá giải mê cung",
  "bong-ro": "18. Game: Bóng rổ",
  "nhay-thung": "19. Game: Nhảy thùng",
  "mo-rong": "20. Tiện ích mở rộng",
  "khai-niem": "Các khái niệm trong Game"
}
