export default {
  "index": { "display": "hidden" },
  "gioi-thieu-rover": "1. Giới thiệu về robot Rover",
  "lap-rap": "2. Hướng dẫn lắp ráp",
  "cai-dat-thu-vien": "3. Cài đặt thư viện",
  "bai-1": "4. Bài 1: Cùng di chuyển nào",
  "bai-2": "5. Bài 2: Chú ý từng bước đi",
  "bai-3": "6. Bài 3: Thắp sáng",
  "bai-4": "7. Bài 4: Trở thành cảnh sát",
  "bai-5": "8. Bài 5: Đôi mắt tinh tường",
  "bai-6": "9. Bài 6: Vượt chướng ngại vật",
  "bai-7": "10. Bài 7: Bám sát mục tiêu",
  "bai-8": "11. Bài 8: Vết tích để lại",
  "bai-9": "12. Bài 9: Lần theo dấu vết",
  "bai-10": "13. Bài 10: Né tránh nguy hiểm",
  "bai-11": "14. Bài 11: Hoàn trả vật phẩm",
  "bai-12": "15. Bài 12: Hạ gục tội phạm",
  "bai-13": "16. Bài 13: Hỗ trợ từ xa",
  "bai-14": "17. Bài 14: Chỉ huy từ xa",
  "bai-15": "18. Bài 15: Giao tiếp cùng đồng đội",
  "bai-16": "19. Bài 16: Lập trình AI - Điều khiển bằng giọng nói",
  "bai-17": "20. Bài 17: Lập trình AI - Điều khiển bằng cử chỉ",
  "bai-18": "21. Bài 18: Điều khiển và giám sát robot qua IoT",
  "che-do-mac-dinh": "Che Do Mac Dinh"
}
