export default {
  "index": { "display": "hidden" },
  "dht20": "1. Cảm biến nhiệt độ độ ẩm DHT20",
  "dht11": "2. Cảm biến nhiệt độ độ ẩm DHT11",
  "do-am-dat": "3. Cảm biến độ ẩm đất",
  "dat-dien-dung": "4. Cảm biến độ ẩm đất điện dung",
  "vat-can": "5. Cảm biến vật cản hồng ngoại",
  "mq2": "6. Cảm biến khí gas MQ2",
  "mq3": "7. Cảm biến nồng độ cồn MQ3",
  "mq135": "8. Cảm biến chất lượng không khí MQ135",
  "ir": "9. Mắt đọc hồng ngoại IR",
  "line-4-mat": "10. Cảm biến dò đường 4 mắt",
  "line-2-mat": "11. Cảm biến dò đường 2 mắt",
  "color": "12. Cảm biến màu sắc",
  "sieu-am": "13. Cảm biến siêu âm",
  "am-thanh": "14. Cảm biến âm thanh",
  "goc-xoay": "15. Cảm biến góc xoay",
  "anh-sang": "16. Cảm biến ánh sáng",
  "lua": "17. Cảm biến lửa",
  "pir": "18. Cảm biến PIR",
  "cham": "20. Cảm biến chạm",
  "nuoc": "20. Cảm biến nước",
  "keypad": "20. Keypad - Bàn phím cảm ứng điện dung",
  "rotary": "22. Cảm biến góc xoay - Rotary Encoder",
  "hx711": "23. Mạch Chuyển Đổi ADC 24bit Loadcell HX711",
  "van-tay": "23. Cảm biến vân tay AS608",
  "gps": "24. Mạch định vị GPS BDS ATGM336H",
  "lora": "25. Mạch thu phát LoRa E32",
  "nhip-tim": "26. Cảm biến nhịp tim và oxy trong máu MAX30102:",
  "nhiet-do-ds18b20": "27. Cảm biến nhiệt độ DS18B20",
  "nhiet-do-hong-ngoai": "28. Cảm biến nhiệt độ hồng ngoại không tiếp xúc",
  "mpu6050": "29. Cảm biến góc MPU6050",
  "dong-dien-ina219": "30. Cảm biến dòng điện INA219",
  "rfid": "31. Module RFID NFC 13.56MHz RC522 I2C",
  "pcf_rtc_8563": "32. Module thời gian thực RTC PCF8563 (Real-Time Clock)",
  "yolobit_ir_blaster": "33. Module IR Blaster (Hồng ngoại phát tín hiệu)",
  "veml6040": "34. Module cảm biến màu VEML6040",
  "bmp280_yolobit": "35. Module cảm biến môi trường BMP280"
}
