export default {
  "index": { "display": "hidden" },
  "gioi-thieu": "1. Giới thiệu về xBuild Creator Kit",
  "setup": "2. Hướng Dẫn Cài Đặt uPyCraft IDE",
  "about-upycraft": "3. Làm quen với phần mềm uPyCraft IDE",
  "lesson1": "4. Bài học 1: Hello world",
  "lesson2": "5. Bài học 2: Blink LED",
  "lesson3": "6. Bài học 3: Nhấn nút bật đèn LED",
  "lesson4": "7. Bài học 4: Điều khiển tốc độ chớp tắt đèn LED",
  "lesson5": "8. Bài học 5: Điều chỉnh độ sáng LED",
  "lesson6": "9. Bài học 6: Đèn LED RGB cảm ứng",
  "lesson7": "10. Bài học 7: Vỗ tay thay đổi màu đèn LED",
  "lesson8": "11. Bài học 8: Phát nhạc với còi báo",
  "lesson9": "12. Bài học 9: Cảm biến gia tốc góc nghiêng",
  "lesson10": "13. Bài học 10: Hiển thị thông tin lên màn hình LCD",
  "lesson11": "14. Bài học 11: Theo dõi nhiệt độ, độ ẩm trên LCD",
  "lesson12": "15. Bài học 12: Remote hồng ngoại",
  "lesson13": "16. Bài học 13: Điều khiển góc quay Servo",
  "intro": "17. Giới thiệu về dự án Nhà thông minh",
  "project1": "18. Project 1: Đèn điều khiển từ xa",
  "project2": "19. Project 2: Quạt thông minh",
  "project3": "20. Project 3: Đèn thông minh",
  "project4": "21. Project 4: Hệ thống chống trộm và báo động",
  "project5": "22. Project 5: Cửa thông minh"
}
