export default {
  "index": { "display": "hidden" },
  "den_thong_minh": "1. Đèn thông minh",
  "dht20": "2. Máy đo nhiệt độ độ ẩm",
  "vuon_thong_minh": "3. Vườn thông minh",
  "thung_rac_thong_minh": "4. Thùng rác thông minh",
  "nut_nhan_doi": "5. Bật/tắt đèn (tiny RGB) bằng nút nhấn đôi",
  "nuoc": "6. Cảm biến nước",
  "am_thanh": "7. Cảm biến âm thanh",
  "relay": "8. Relay",
  "keypad": "9. Keypad - Bàn phím cảm ứng điện dung",
  "ir": "10. Mắt đọc IR và Remote",
  "lua": "11. Cảm biến lửa",
  "mpu6050": "12. Cảm biến góc MPU6050",
  "goc_xoay": "13. Cảm biến góc xoay",
  "coi_bao": "14. Còi báo",
  "gps_ATGM336H": "15. Mạch định vị GPS BDS ATGM336H",
  "rtc_8563": "16. Module thời gian thực RTC PCF8563 (Real-Time Clock)",
  "bmp280": "17. Module cảm biến môi trường BMP280",
  "ir_blaster": "18. Module IR Blaster (Hồng ngoại phát tín hiệu)",
  "lorae32": "19. Module truyền nhận không dây LoRa E32 (SX1278)",
  "sht30": "20. SHT30 - Cảm biến nhiệt độ và độ ẩm",
  "uv_s12sd": "21. GUVA-S12SD - Module cảm biến ánh sáng UV",
  "acd1100": "22. ACD1100 - Module cảm biến CO₂ Nồng Độ Cao",
  "dc01_pm2-5": "23. DC01 - Module cảm biến bụi PM2.5 hồng ngoại (UART)"
}
