export default {
  "index": { "display": "hidden" },
  "gioi_thieu": "1. Giới thiệu về Stem Starter Kit",
  "tai_thu_vien": "2. Cài đặt thư viện STEM KIT",
  "den_giao_thong": "3. Đèn giao thông",
  "may_rua_tay": "4. Máy rửa tay không chạm",
  "bai_dau_xe": "5. Bãi đậu xe thông minh",
  "gay_thong_minh": "6. Gậy thông minh cho người khiếm thị",
  "may_bao_khi_gas": "7. Máy cảnh báo khí gas",
  "den_hoc_thong_minh": "8. Đèn học thông minh",
  "thung_rac_thong_minh": "9. Thùng rác thông minh",
  "cua_thong_minh": "10. Cánh cửa thông minh",
  "chau_cay_thong_minh": "11. Chậu cây thông minh",
  "tro_luon_day": "12. Trò chơi luồn dây",
  "vong_quay": "13. Vòng quay may mắn",
  "may_ban_da": "14. Máy bắn đá",
  "cap_treo": "15. Cáp treo",
  "robot_cao_cao": "16. Cuộc đua robot cào cào",
  "robot_tu_xa": "17. Robot điều khiển từ xa",
  "robot_ne_vat": "18. Robot né vật",
  "robot_gap_vat": "19. Robot gắp vật",
  "thuyen_dien": "20. Thuyền điện",
  "robot_sau_do": "21. Robot sâu đo",
  "ban_tay_mo_phong": "22. Bàn tay mô phỏng",
  "robot-do-duong": "23. Robot dò đường"
}
